version: "1.0"

services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - ./:/data/db_bank
    ports:
      - "5002:5432"

  db-test:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASETEST}
    volumes:
      - ./:/data/db-test
    ports:
      - "5003:5432"